source 'https://rubygems.org'

gem 'sinatra'
gem 'puma'
gem 'jwt'
gem 'json'
gem 'yard'
gem 'rspec'
gem 'ci_reporter_rspec'
gem 'sinatra-contrib'

# Database
# gem 'mongoid', '~>4.0' # MongoDB driver
# gem 'mongoid-pagination', '~>0.2' # Pagination library