swagger: "2.0"
info:
  title: "SONATA's SP API"
  description: "This is a proposal for the SONATA's SP API"
  version: "1.0.0"
host: sp.sonata-nfv.eu
schemes:
  - https
basePath: /api
produces:
  - application/json

paths:
  /:
    get:
      summary: "Gatekeeper's URL root"
      description: "Everything starts here."
      parameters:
      tags:
      responses:
        '200':
          description: 'This list of paths.'
  /api-doc:
    get:
      summary: "Gatekeeper's API documentation."
      description: "The Gatekeeper's API documentation, in Swagger format."
      produces:
        - text/html
      parameters:
      tags:
      responses:
        '200':
          description: "This HTML API documentation."
  /packages:
    post:
      summary: "Submit a SONATA package to the Service Platform."
      description: "The SDK uses this endpoint to submit a SONATA package."
      produces:
        - application/json
      parameters:
        - name: "package"
          in: "formData"
          description: "The Package file, as specified by the son-schema."
          required: true
          type: file
      tags: 
      responses:
        '201':
          description: "The submited package has been received, validated and submited to the Catalogue."
  /instantiations:
    get:
      summary:
    post:
      summary:
