---
development:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

test:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

production:
  pkgmgmt:
    url: 'http://localhost:5100/packages'
  licenses: ''
  users: ''
  kpis: ''
  bss: ''

