"""empty message

Revision ID: 4c2e7343ae90
Revises: efe1265647a4
Create Date: 2016-12-17 15:43:42.561486

"""

# revision identifiers, used by Alembic.
revision = '4c2e7343ae90'
down_revision = 'efe1265647a4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('type_uuid', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('type_uuid')
    )
    op.create_table('license',
    sa.Column('type_uuid', sa.String(), nullable=False),
    sa.Column('service_uuid', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('license_uuid', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('startingDate', sa.DateTime(), nullable=True),
    sa.Column('expiringDate', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['type_uuid'], ['type.type_uuid'], ),
    sa.PrimaryKeyConstraint('license_uuid')
    )
    op.drop_table('service')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('service_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiringDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('startingDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('external_service_uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('service_uuid', name=u'service_pkey'),
    sa.UniqueConstraint('external_service_uuid', name=u'service_external_service_uuid_key')
    )
    op.drop_table('license')
    op.drop_table('type')
    ### end Alembic commands ###
