"""empty message

Revision ID: 91be5ef3c0c1
Revises: 
Create Date: 2016-11-21 14:55:53.732858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91be5ef3c0c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('service_uuid', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expiringDate', sa.DateTime(), nullable=False),
    sa.Column('startingDate', sa.DateTime(), nullable=False),
    sa.Column('external_service_uuid', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('service_uuid'),
    sa.UniqueConstraint('external_service_uuid')
    )
    op.create_table('type',
    sa.Column('type_uuid', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('type_uuid')
    )
    op.create_table('license',
    sa.Column('type_uuid', sa.String(), nullable=False),
    sa.Column('service_uuid', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('license_uuid', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('startingDate', sa.DateTime(), nullable=True),
    sa.Column('expiringDate', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['service_uuid'], ['service.service_uuid'], ),
    sa.ForeignKeyConstraint(['type_uuid'], ['type.type_uuid'], ),
    sa.PrimaryKeyConstraint('license_uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license')
    op.drop_table('type')
    op.drop_table('service')
    ### end Alembic commands ###
