"""empty message

Revision ID: f6eb785cf122
Revises: None
Create Date: 2017-01-20 14:11:00.827771

"""

# revision identifiers, used by Alembic.
revision = 'f6eb785cf122'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('type_uuid', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('type_uuid')
    )
    op.create_table('license',
    sa.Column('type_uuid', sa.String(), nullable=False),
    sa.Column('service_uuid', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('license_uuid', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('startingDate', sa.DateTime(), nullable=True),
    sa.Column('expiringDate', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['type_uuid'], ['type.type_uuid'], ),
    sa.PrimaryKeyConstraint('license_uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license')
    op.drop_table('type')
    ### end Alembic commands ###
