# Generated by cucumber-sinatra. (2016-02-01 23:48:52 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app', 'son_gtk_gui.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = SonGtkGui

class SonGtkGuiWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SonGtkGuiWorld.new
end
