source 'http://rubygems.org'
ruby "2.4.3"
gem 'rake', '11.2.2'
gem 'sinatra', '1.4.7', require: 'sinatra/base'
gem 'sinatra-contrib', '1.4.7', require: false
gem 'puma', '3.11.0'
gem 'rest-client', '2.0.0'
gem 'rack-parser', '0.7.0', require: 'rack/parser'
gem 'sinatra-cross_origin', '0.3.2'
gem 'ci_reporter_rspec', '1.0.0'
gem 'rubyzip', '1.2.1'
gem 'foreman', '0.82.0'
gem 'addressable', '2.4.0'
gem 'rubocop', '0.49.0'
gem 'rubocop-checkstyle_formatter', '0.3.0', require: false
gem 'sinatra-logger', '0.1.1'
gem 'curb', '0.9.3'
gem 'factory_girl', '4.8.0'
gem 'activesupport', '5.0.2', :require => "active_support"
gem 'SONATA', '0.1.0', path: './lib/local-gems'

group :test do
  gem 'webmock', '2.1.0'
  gem 'rspec', '3.5.0'
  gem 'rack-test', '0.6.3'
  gem 'rspec-its', '1.2.0'
end

group :test, :development do
  gem 'capybara', '2.7.1'
end

