source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'pry'
gem 'pry-byebug'
gem 'puma'
gem 'rest-client'
gem 'rack-parser', :require => 'rack/parser'

group :test do
  gem 'webmock'
  gem 'rspec'
  gem 'rack-test'
end

group :test, :development do
  gem 'capybara'
end
