source 'https://rubygems.org'

gem 'rake'
gem "sinatra", "~> 1.4.3", require: 'sinatra/base'
gem "sinatra-contrib", "~> 1.4.1", require: false
gem 'pry'
#gem 'pry-byebug'
gem 'puma'
gem 'rest-client'
gem 'rack-parser', :require => 'rack/parser'
gem 'sinatra-cross_origin'
gem 'ci_reporter_rspec'
gem 'rubyzip', '>= 1.0.0'

group :test do
  gem 'webmock'
  gem 'rspec'
  gem 'rack-test'
  gem 'rspec-its'
end

group :test, :development do
  gem 'capybara'
end
