## Copyright 2015-2017 Portugal Telecom Inovacao/Altice Labs
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'
require_relative './gtk_api'

task default: ['ci:all']

desc 'Run Unit Tests'
RSpec::Core::RakeTask.new :specs do |task|
  task.pattern = Dir['spec/**/*_spec.rb']
end

# use like in
#   rake ci:all
namespace :ci do
  task all: ['ci:setup:rspec', 'specs']
end

desc 'Run the specs whenever a relevant file changes.'
task :watch do
  system 'watchr watch.rb'
end
