---
development:
  catalogues:
    url: 'http://localhost:5200/catalogues'

test:
  catalogues:
    url: 'http://localhost:5200/catalogues'

integration:
  catalogues:
    url: 'http://sp.int.sonata-nfv.eu:4002/catalogues'

qualification:
  catalogues:
    url: 'http://localhost:5200/catalogues'

demonstration:
#production:
  catalogues:
    url: 'http://localhost:5200/catalogues'
  